version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  whisper:
    lang: python3-http-debian
    handler: ./whisper
    image: docker.io/welteki/whisper:latest
    build_args:
      ADDITIONAL_PACKAGE: "ffmpeg"
    annotations:
      com.openfaas.profile: gpu
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 2m
    environment:
      write_timeout: 30m5s
      exec_timeout: 30m

